url: https://edwardwijaya.github.io
baseurl:

# Site settings
title: Edward Wijaya
email: edward.lucius@gmail.com
description: "I am a multidisciplinary engineer with expertise in development and implementation in automated builds, deployment pipelines and scaling workflows to handle huge number of hosts in multiple Datacenters. In the same time i’m  the Site Reliability of Apple services serving massive world facing requests."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Person name, titles and social links
people:
- name: Edward Wijaya
  pic: 1
  position: Senior Site Reliability Engineer
  social:
    - title: linkedin
      url: http://www.linkedin.com/pub/edward-wijaya/27/478/935
    - title: facebook
      url: https://www.facebook.com/edward.lucius
    - title: github
      url: https://github.com/edwardwijaya


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: linkedin
      url: http://www.linkedin.com/pub/edward-wijaya/27/478/935
    - title: facebook
      url: https://www.facebook.com/edward.lucius
    - title: github
      url: https://github.com/edwardwijaya

# Postal address (add as many lines as necessary)
address:
  - line: 125 Compassvale Bow
  - line: Singapore, 544820

# Build settings
markdown: kramdown
permalink: pretty
