url: https://edwardwijaya.github.io
baseurl:

# Site settings
title: Edward Wijaya
email: edward.wijaya@windowslive.com
description: "Hi, my name is Edward. I'm an enthusiastic Software Engineer and Analytical person. Backend Development & Automation CI are my forte. Especially interested in tech topics such as, scalable web systems & servers. I'm also currently learning Mobile platforms, and web products such as Google/Facebook products."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Person name, titles and social links
people:
- name: Edward Wijaya
  pic: 1
  position: Solution Engineer / Team Lead
  social:
    - title: linkedin
      url: http://www.linkedin.com/pub/edward-wijaya/27/478/935
    - title: facebook
      url: https://www.facebook.com/edward.lucius
    - title: github
      url: https://github.com/edwardwijaya


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: linkedin
      url: http://www.linkedin.com/pub/edward-wijaya/27/478/935
    - title: facebook
      url: https://www.facebook.com/edward.lucius
    - title: github
      url: https://github.com/edwardwijaya

# Postal address (add as many lines as necessary)
address:
  - line: 29 Hillview Avenue
  - line: Singapore, 669561

# Build settings
markdown: kramdown
permalink: pretty